### ISSUE TITLE
gmock/gtest cannot be found

### ISSUE THREAD

**Issue by acxz** [ros-noetic-arch/ros-noetic-catkin#1]
See upstream issue: https://github.com/ros/catkin/issues/1030

**Comment by hadogenes** [comment]
after last update I have error while building _ros-noetic-realtime-tools_:
```
-- BUILD_SHARED_LIBS is on
-- Found Threads: TRUE  
CMake Warning at /opt/ros/noetic/share/catkin/cmake/test/gtest.cmake:160 (message):
  skipping gmock 'realtime_box_tests' in project 'realtime_tools' because
  gmock was not found
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/test/gtest.cmake:89 (_catkin_add_executable_with_google_test)
  /opt/ros/noetic/share/catkin/cmake/test/gtest.cmake:63 (_catkin_add_google_test)
  CMakeLists.txt:23 (catkin_add_gmock)


CMake Error at CMakeLists.txt:24 (target_link_libraries):
  Cannot specify link libraries for target "realtime_box_tests" which is not
  built by this project.
```

**Comment by acxz** [comment]
Just to make sure can you run 'yay -Syu ros-noetic-realtime-tools --rebuildtree'?

**Comment by hadogenes** [comment]
I always build from scratch - I use jenkins and have minimal docker image.
One thing I'm building for _manjaro_, so some packages can be outdated to _arch._

**Comment by acxz** [comment]
ah thats probably why then can you check what version of the `gtest` package you are on?

Edit just checked, Manjaro is using an older gtest version: 1.8.1, while Arch is on gtest 1.10.0

I recommend using an Arch repo compatible distro, such as [EndeavourOS](https://endeavouros.com/) which we do support instead of an Arch based one like Manjaro.
If the reason you choose Manjaro over Arch because of the GUI installer, dont worry EndeavourOS also has a GUI installer.

**Comment by acxz** [comment]
The patch has been released in the latest version 0.8.7. Closing this issue.

**Comment by hadogenes** [comment]
I confirm it was due to gtest version. After updating to v1.10, it builds correctly.
PS I've used gentoo before, so the lack of an installer doesn't scare me. I want a bit more stability than arch.

**Comment by acxz** [comment]
Glad to hear it works!

Well as you just experienced you won't find stability with the AUR ROS packages and Manjaro repos.
