### ISSUE TITLE
Incorrect dependency name

### ISSUE THREAD

**Issue by WysokiStudent** [ros-noetic-arch/ros-noetic-catkin#2]
Dependency check fails with 
```
:: python-catkin-pkg not found.
:: Dependency not found: python-catkin-pkg
:: python-catkin-pkg not found.
:: Dependency not found: python-catkin-pkg
```
The package in AUR is called `python-catkin_pkg`. I suspect the published name should be changed to `python-catkin-pkg` instead of changing the dependency to point to  `python-catkin_pkg`.

**Comment by acxz** [comment]
`python-catkin_pkg` provides `python-catkin-pkg`.
If you are compiling manually or using any decent AUR helper (we test with `yay`) it should work just fine.

I believe you should file a bug at the AUR helper you are using.

Please feel free to reopen this issue if the problem still persists.

**Comment by WysokiStudent** [comment]
You are right, trizen failed whereas yay succeeded.

**Comment by acxz** [comment]
Glad to hear it worked!
